
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y gnupg

RUN groupadd -r mysql && useradd -r -g mysql mysql

RUN { \
    #Set MySQL root password for silent installation
    echo mysql-community-server mysql-community-server/root-pass password ''; \
    echo mysql-community-server mysql-community-server/re-root-poss password ''; \
    } | debconf-set-selections \
    && apt-get install -y mysql-server \
    && mkdir -p /var/lib/mysql /var/run/mysqld \
    && chown -R mysql:mysql /var/lib/mysql /var/run/mysqld \
    && chmod 777 /var/run/mysqld \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#Solve the problem that ubuntu cannot log in from another container
RUN sed -i 's/bind-address/#bind-address/' /etc/mysql/mysql.conf.d/mysqld.cnf

# EXPOSE 3306

COPY entrypoint_db.sh /entrypoint_db.sh
RUN chmod +x /entrypoint_db.sh

ENTRYPOINT ["/entrypoint_db.sh"]
