FROM ubuntu:mantic

RUN apt-get update && \
    apt-get install -y \
    php-fpm \
    php-mysql \
    wget \
    unzip

WORKDIR /var/www/html
RUN wget https://wordpress.org/latest.tar.gz && \
    tar -xzvf latest.tar.gz && \
    rm latest.tar.gz
