FROM ubuntu:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    php-fpm \
    php-common \
    php-mbstring \
    php-gd \
    php-intl \
    php-xml \
    php-mysql \
    wget \
    sudo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 9000

WORKDIR /var/www/

RUN wget http://wordpress.org/latest.tar.gz && \
    tar xzvf latest.tar.gz

WORKDIR /var/www/wordpress

RUN cp wp-config-sample.php wp-config.php

CMD sed -i -e "s/database_name_here/$WORDPRESS_DB_NAME/" wp-config.php && \
    sed -i -e "s/username_here/$WORDPRESS_DB_USER/" wp-config.php && \
    sed -i -e "s/password_here/$WORDPRESS_DB_PASSWORD/" wp-config.php && \
    sed -i -e "s/localhost/$WORDPRESS_DB_HOST/" wp-config.php && \
    echo "[www]\nlisten = 9000" >> /etc/php/8.1/fpm/php-fpm.conf && \
    php-fpm8.1 -F -O
