FROM ubuntu:latest

ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=my_user
ENV MYSQL_PASSWORD=my_password

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER $MYSQL_USER:$MYSQL_USER

EXPOSE 3306

CMD ["service", "mysql", "start"]
