# Use a custom Ubuntu base image
FROM ubuntu:latest

# Install necessary packages and clean up
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Copy custom MySQL configuration file, if needed
# COPY my.cnf /etc/mysql/my.cnf

# Start MySQL service on container startup
CMD ["mysqld"]
